application:
  host: '0.0.0.0'
  port: 8000
  base_url: 'https://api.pnar.world'
  request_timeout_seconds: 30
  max_request_size: 2097152 # 2MB
  workers: null # Auto-detect
  cors:
    allowed_origins: ['https://pnar.world', 'https://www.pnar.world']
    allowed_methods: ['GET', 'POST', 'PUT', 'DELETE', 'OPTIONS', 'PATCH']
    allowed_headers: ['Content-Type', 'Authorization', 'X-Requested-With']
    allow_credentials: true
    max_age: 86400 # 24 hours

database:
  username: 'postgres'
  password: 'root'
  port: 5432
  host: 'localhost'
  database_name: 'pnar_world'
  require_ssl: false
  max_connections: 10
  min_connections: 1
  connect_timeout_seconds: 10
  idle_timeout_seconds: 600
  max_lifetime_seconds: 1800

jwt:
  secret: '${JWT_SECRET}'
  expires_in_minutes: 15 # Shorter in production
  refresh_expires_in_days: 7
  cookie_name: 'auth_token'
  cookie_domain: '.pnar.world'
  cookie_secure: true
  cookie_http_only: true
  cookie_same_site: 'Strict'

logging:
  level: 'info'
  format: 'json'
  file_path: '/var/log/pnar-world-api.log'
  max_file_size_mb: 100
  max_files: 10

security:
  rate_limit_requests_per_minute: 100
  rate_limit_burst: 20
  password_min_length: 12
  password_require_special_chars: true
  password_require_numbers: true
  password_require_uppercase: true
  session_timeout_minutes: 30
  max_login_attempts: 3
  lockout_duration_minutes: 30
  trusted_proxies: ['10.0.0.0/8', '172.16.0.0/12', '192.168.0.0/16']

monitoring:
  metrics_enabled: true
  health_check_interval_seconds: 15
  performance_monitoring: true
  error_reporting: true
