application:
  host: '127.0.0.1'
  port: 8000
  base_url: 'http://localhost:8000'
  request_timeout_seconds: 30
  max_request_size: 1048576 # 1MB
  workers: null # Auto-detect based on CPU cores
  cors:
    allowed_origins: ['*']
    allowed_methods: ['GET', 'POST', 'PUT', 'DELETE', 'OPTIONS', 'PATCH']
    allowed_headers: ['Content-Type', 'Authorization', 'X-Requested-With']
    allow_credentials: true
    max_age: 3600

database:
  username: 'postgres'
  password: 'root'
  port: 5432
  host: '127.0.0.1'
  database_name: 'pnar_world'
  require_ssl: false
  max_connections: 10
  min_connections: 1
  connect_timeout_seconds: 10
  idle_timeout_seconds: 600
  max_lifetime_seconds: 1800

jwt:
  secret: 'your-secret-key-here-change-me-in-production'
  expires_in_minutes: 60
  refresh_expires_in_days: 7
  cookie_name: 'auth_token'
  cookie_domain: null
  cookie_secure: false
  cookie_http_only: true
  cookie_same_site: 'Lax'

logging:
  level: 'info'
  format: 'json'
  file_path: null
  max_file_size_mb: 100
  max_files: 5

security:
  rate_limit_requests_per_minute: 60
  rate_limit_burst: 10
  password_min_length: 8
  password_require_special_chars: true
  password_require_numbers: true
  password_require_uppercase: true
  session_timeout_minutes: 60
  max_login_attempts: 5
  lockout_duration_minutes: 15
  trusted_proxies: []

monitoring:
  metrics_enabled: true
  health_check_interval_seconds: 30
  performance_monitoring: true
  error_reporting: true
