application:
  # Host address - use 0.0.0.0 in container, 127.0.0.1 locally
  host: "127.0.0.1"
  port: 8000
  base_url: "http://localhost:8000"
  cors:
    allowed_origins: ["*"]
    allowed_methods: ["GET", "POST", "PUT", "DELETE", "OPTIONS"]
    allowed_headers: ["*"]
    allow_credentials: true

database:
  username: "postgres"
  password: "root"
  port: 5432
  host: "127.0.0.1"  # Default to localhost
  database_name: "pnar_world"
  require_ssl: false
  max_connections: 10

jwt:
  # Make sure to set this in production
  secret: "your-secret-key-here-change-me-in-production"
  expires_in_minutes: 60
  refresh_expires_in_days: 7
  cookie_name: "auth_token"
  # Set domain in production
  cookie_domain: null
  cookie_secure: false

logging:
  # Set to info in production, debug in development
  level: "info"
  format: "json"