apiVersion: v1
kind: Pod
metadata:
  name: pw-pod
spec:
  containers:
    # 1. PostgreSQL Database
    - name: postgres
      image: postgres:15-alpine
      env:
        - name: POSTGRES_USER
          value: postgres
        - name: POSTGRES_PASSWORD
          value: root
        - name: POSTGRES_DB
          value: pnar_world
      ports:
        - containerPort: 5432
          hostPort: 5432

    # 2. PgAdmin
    - name: pgadmin
      image: docker.io/dpage/pgadmin4:7.8
      securityContext:
        runAsUser: 5050
      env:
        - name: PGADMIN_DEFAULT_EMAIL
          value: admin@pnar.online
        - name: PGADMIN_DEFAULT_PASSWORD
          value: root
        - name: PGADMIN_LISTEN_ADDRESS
          value: "0.0.0.0"
      ports:
        - containerPort: 80
          hostPort: 9001

    # 3. Rust API
    - name: api
      image: pnar-world-api:1.0.0
      env:
        - name: DATABASE_URL
          value: postgres://postgres:root@postgres:5432/pnar_world
        - name: RUST_LOG
          value: debug
      ports:
        - containerPort: 8000
          hostPort: 8000
