apiVersion: v1
kind: Pod
metadata:
  name: pnar-app-pod
spec:
  containers:
    # PostgreSQL Database
    - name: postgres
      image: postgres:15-alpine
      env:
        - name: POSTGRES_USER
          value: postgres
        - name: POSTGRES_PASSWORD
          value: root
        - name: POSTGRES_DB
          value: pnar_world
        - name: PGDATA
          value: /var/lib/postgresql/data/pgdata
      ports:
        - containerPort: 5432
          hostPort: 5432
      volumeMounts:
        - name: postgres-data
          mountPath: /var/lib/postgresql/data

    # Adminer - Lightweight Database Client
    - name: adminer
      image: adminer:4.8.1
      env:
        - name: ADMINER_DEFAULT_SERVER
          value: localhost
        - name: ADMINER_DESIGN
          value: pepa-linha-dark
      ports:
        - containerPort: 8080
          hostPort: 8080

    # PNAR World Rust API
    - name: api
      image: pnar-world-api:1.0.0
      env:
        - name: APP_HOST
          value: 0.0.0.0
        - name: APP_PORT
          value: '8000'
        - name: DB_HOST
          value: localhost
        - name: DB_PORT
          value: '5432'
        - name: DB_USER
          value: postgres
        - name: DB_PASSWORD
          value: root
        - name: DB_NAME
          value: pnar_world
        - name: DB_SSL
          value: 'false'
        - name: RUST_LOG
          value: debug
        - name: APP_ENVIRONMENT
          value: development
      ports:
        - containerPort: 8000
          hostPort: 8000

  volumes:
    - name: postgres-data
      emptyDir: {}
