application:
  host: "127.0.0.1"
  port: 8000
  base_url: "http://localhost:8000"
  cors:
    allowed_origins: ["*"]
    allowed_methods: ["GET", "POST", "PUT", "DELETE", "OPTIONS"]
    allowed_headers: ["*"]
    allow_credentials: true

database:
  username: "postgres"
  password: "root"
  port: 5432
  host: "localhost"
  database_name: "pnar_world"
  require_ssl: false
  max_connections: 10

jwt:
  secret: "your-secret-key-here-change-me-in-production"
  expires_in_minutes: 60
  refresh_expires_in_days: 7
  cookie_name: "auth_token"
  cookie_domain: null
  cookie_secure: false

logging:
  level: "info"
  format: "json"
