name: SSH Connect Test

on:
  workflow_dispatch:

jobs:
  ssh-test:
    name: SSH connectivity test
    runs-on: ubuntu-latest
    steps:
      - name: Prepare SSH key and known_hosts
        shell: bash
        run: |
          set -euo pipefail
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          if [ -n "${{ secrets.SSH_KNOWN_HOSTS }}" ]; then
            echo "${{ secrets.SSH_KNOWN_HOSTS }}" > ~/.ssh/known_hosts
            chmod 644 ~/.ssh/known_hosts
          else
            if [ -n "${{ secrets.SSH_HOST }}" ]; then
              ssh-keyscan -p "${{ secrets.SSH_PORT || 22 }}" "${{ secrets.SSH_HOST }}" >> ~/.ssh/known_hosts || true
              chmod 644 ~/.ssh/known_hosts || true
            fi
          fi

      - name: Test SSH connectivity (verbose)
        shell: bash
        run: |
          set -euo pipefail
          echo "Running ssh -i ~/.ssh/id_rsa -o IdentitiesOnly=yes -o StrictHostKeyChecking=yes -p ${${{ secrets.SSH_PORT || 22 }}} ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}"
          ssh -i ~/.ssh/id_rsa -o IdentitiesOnly=yes -o StrictHostKeyChecking=yes -p "${{ secrets.SSH_PORT || 22 }}" "${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}" \
            'echo CI_SSH_OK; uname -a; date'
